id: default

############################################################################
# Доступные команды                                                        #
############################################################################
# Дропнуть случайный предмет: [DROP] количество
# Нанести удар ближайшим игрокам: [DAMAGE_NEAR] урон радиус
# Отправить всем сообщение [MSG] Ваше сообщение
# Отправить ближайшим сообщение [MSG_NEAR] Ваше сообщение --radius:Радиус
# Отправить всем игрокам тайтл [TITLE] Заголовок;Подзаголовок
# Отправить ближайшим игрокам тайтл [TITLE_NEAR] Заголовок;Подзаголовок --radius:Радиус
# Отправить команду от имени консоли [CONSOLE] command
# Очистить оставшиеся лут на земле от ивента [DROP_CLEAR]
# Воспроизвести звук всем игрокам [SOUND] SOUND_NAME;Громкость;Подача
# Воспроизвести звук ближайшим игрокам [SOUND_NEAR] SOUND_NAME;Громкость;Подача радиус
# Выдать всем игрокам эффект [EFFECT] EFFECT_NAME;Сила;Длительность
# Выдать ближайшим игрокам эффект [EFFECT_NEAR] EFFECT_NAME;Сила;Длительность радиус
# Подождать несколько тиков перед выполнением следующей команды [DELAY] время_в_тиках
############################################################################
# Боссбары                                                                 #
############################################################################
# Создать боссбар [CREATE_BOSSBAR] id
# Показать всем на сервере [SHOW_BOSSBAR] id
# Показать ближайшим игрокам [SHOW_BOSSBAR_NEAR] id radius
# Скрыть боссбар ближайшим игрокам [REMOVE_BOSSBAR_NEAR] id radius
# Скрыть боссбар всем на сервере [REMOVE_BOSSBAR] id
# Удалить боссбар [DELETE_BOSSBAR]
#
# Пример использования:
# Например когда активен ивент (onStart)
# - [CREATE_BOSSBAR] example
# - [SHOW_BOSSBAR_NEAR] example 20
# А когда ивент завершается (onEnd)
# - [DELETE_BOSSBAR] example
############################################################################

mask:
  # Включить маскировку предметов при дропе?
  enable: true
  items:
    # Тут настраивается маскировка.
    # Для маскировки дропа будет выбрана случайная маска
    m1: # название может быть любым
      material: COBWEB
      enchanted: true
      name: "&#0EC8E2&k|||||||||"
    m2:
      material: PHANTOM_MEMBRANE
      enchanted: true
      name: "&#0EC8E2&k|||||||||"


# Можно юзать такие плейсхолдеры как
# %time_to_next_drop% - время до следующего дропа предмета
# %time_to_next_phase% - время до следующей фазы (если включён phase)
# %time_to_end% - время до конца ивента
bossBars:
  example:
    title: "Пример"
    # Доступно: PINK, BLUE, RED ,GREEN ,YELLOW ,PURPLE, WHITE
    Color: BLUE
    # Доступно: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
    Style: PROGRESS
    # Время спустя которое боссбар исчезнет
    # Если оставить -1 то боссбар пропадёт когда ивент завершится
    duration: -1

# Фазы это когда если время до завершения вулкана остаётся столько-то секунд, то выполнять такие-то действия.
phase:
  enable: false
  phases:
    '30': # Тайминг - сколько осталось до конца ивента
      # Если до конца ивента == 30 секунд то один раз выполняются команды ниже
      - '[DROP] 1'
    '1':
      - '[DROP] 5'

region:
  enable: true
  size: 25
  flags:
    - "pvp allow"
    - "tnt deny"
    - "deny-message &cВы не можете это сделать в регионе ивента."
    - "blocked-cmds sethome,setwarp"

# Схематика
schem:
  enable: true
  # Имя схематики которое должно находится в папке "schematics"
  file: default.schem
  ignore-air-blocks: true
  offsets-x: 0
  offsets-y: 1
  offsets-z: 0


# Оффсет голограмы
holo-offsets:
  x: 0.5
  y: 2.5
  z: 0.5

hologram:
  - "&dВулкан"
  - "&fИдёт активация"
  - "До подарков: &6{time} сек."
hologram-activated:
  - "&dВулкан"
  - "&fАктивирован"
  - "До удаления: &6{time} сек."


# Сколько нужно онлайна минимум чтобы ивент начался
minPlayers: 1

# Сколько будет длится активация (Время до дропа подарков)
activation: 300
# Сколько будет длится дроп ресурсов
duration: 120
#Радиус выброса ресурсов
radius: 5.0
# Интервал дропа предметов
period: 5
#Сколько тиков должно пройти, прежде чем игрок сможет подобрать выброшенный предмет?
pickup-delay: 40
#
# Настройка частиц при дропе
#
particle:
  enable: true
  fired: false # Предмет будет гореть
  sound: block_lava_extinguish # название звука
  soundPitch: 1.0
  soundVolume: 1.0
  particle-type: FLAME
  #Количество частиц, создаваемых при выбросе ресурсов во время его полета
  particle-amount: 1
  #Минимальная высота выбрасывания
  min-y: 5.0
  #Максимальная высота выбрасывания
  max-y: 10.0
  #Минимальная горизонтальная скорость
  min-horizontal-speed: 0.5
  #Максимальная горизонтальная скорость
  max-horizontal-speed: 1.0

events:
  onSpawn:
    - '[MSG] '
    - '[MSG] &#FB3D14╔══╦══╦══╦══╦══╦══╦══╦══╗'
    - '[MSG] &#FB3D14║ &k|&r&#FB3D14 [Вулкан] &k|'
    - '[MSG] &#FB3D14║ &fУровень лута: &7Обычный'
    - '[MSG] &#FB3D14║ &fУже появился на координатах &a {x} {y} {z}'
    - '[MSG] &#FB3D14║ '
    - '[MSG] &#FB3D14╚══╩══╩══╩══╩══╩══╩══╩══╝'
    - '[MSG] '
  onStart:
    - '[MSG] '
    - '[MSG] &#FB3D14╔══╦══╦══╦══╦══╦══╦══╦══╗'
    - '[MSG] &#FB3D14║ &k|&r&#FB3D14 [Вулкан] &k|'
    - '[MSG] &#FB3D14║ &fУровень лута: &7Обычный'
    - '[MSG] &#FB3D14║ &fУже активировался и начал разрбрасывать лут на координатах &a {x} {y} {z}'
    - '[MSG] &#FB3D14║ '
    - '[MSG] &#FB3D14╚══╩══╩══╩══╩══╩══╩══╩══╝'
    - '[MSG] '
  onEnd:
    - '[DROP_CLEAR]'


#
# Настройки спавна
#
static-location:
  enable: false # Если включит статическую локацию то вулкан будет появляться только на этих координатах
  world: world
  x: 100
  y: 64
  z: 100

# Блок над которым не может появиться вулкан
blacklist-materials:
  - WATER
  - LAVA
  - FIRE
  - ICE
  - BLUE_ICE
  - PACKED_ICE
# Если статическая локация отключена то будет поиск случайных координат
# Настройки случайных координат
spawn-world: world
spawn-radius-min: -2000
spawn-radius-max: 2000

# Использовать заранее сгенерированные локации
use-pre-generated-locations: false